Evaluation/Models/Utils/Authentication.cs
namespace Evaluation.Models.Utils
{
    public class Authentication
    {
    }
}

Evaluation/Models/Utils/ChargeContext.cs
using Evaluation.Models.Cnx;

namespace Evaluation.Models.Utils
{
    public class ChargeContext
    {
        private readonly PsqlContext _psqlContext;

        public ChargeContext(PsqlContext psqlContext)
        {
            _psqlContext = psqlContext;
        }

        public void PreloadData()
        {
            //var personUtils = _psqlContext.PersonUtils.ToList();
        }

        public static void Main(IServiceProvider serviceProvider)
        {
            using(var scope = serviceProvider.CreateScope())
            {
                var context = scope.ServiceProvider.GetRequiredService<PsqlContext>();
                var chargeContext = new ChargeContext(context);
                chargeContext.PreloadData();
            }
        }
    }
}

Evaluation/Models/Utils/Export.cs
using PuppeteerSharp;
using PuppeteerSharp.Media;

namespace Evaluation.Models.Utils
{
    public class Export
    {
        public static async Task<Stream> ExportPdfAsync(string htmlContent)
        {
            var launchOptions = new LaunchOptions
            {
                Headless = true,
                ExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
            };

            await using var browser = await Puppeteer.LaunchAsync(launchOptions);
            await using var page = await browser.NewPageAsync();

            await page.SetContentAsync(htmlContent);

            //await Task.Delay(1000);

            var pdfOptions = new PdfOptions
            {
                Format = PaperFormat.A4,
                PrintBackground = true
            };

            var pdfStream = await page.PdfStreamAsync(pdfOptions);
            pdfStream.Position = 0;

            return pdfStream;
        }

        public static async Task<Stream> ExportPdfAsync(string htmlContent, PaperFormat paperFormat)
        {
            var launchOptions = new LaunchOptions
            {
                Headless = true,
                ExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
            };

            await using var browser = await Puppeteer.LaunchAsync(launchOptions);
            await using var page = await browser.NewPageAsync();

            await page.SetContentAsync(htmlContent);

            //await Task.Delay(1000);

            var pdfOptions = new PdfOptions
            {
                Format = paperFormat,
                PrintBackground = true
            };

            var pdfStream = await page.PdfStreamAsync(pdfOptions);
            pdfStream.Position = 0;

            return pdfStream;
        }

    }
}

Evaluation/Models/Utils/Functions.cs
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq.Dynamic.Core;
using System.Reflection;
using System.Security.Claims;
using CsvHelper;
using CsvHelper.Configuration;
using Microsoft.AspNetCore.Identity;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Processing;

namespace Evaluation.Models.Utils
{
    public class Functions
    {

        public static string GenerateFileName(IFormFile file)
        {
            if (file == null)
            {
                return "no_image.jpg";
            }
            else
            {
                return Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
            }
        }
        public static async void UpdloadImageAsync(IWebHostEnvironment hostEnvironment, string yourFolder, string imageName, IFormFile imageFile)
        {
            if (imageFile != null)
            {
                var wwwRootPath = hostEnvironment.WebRootPath;
                var imageUploadFolder = Path.Combine(wwwRootPath, yourFolder);
                if (!Directory.Exists(imageUploadFolder))
                {
                    Directory.CreateDirectory(imageUploadFolder);
                }
                var imageFilePath = Path.Combine(imageUploadFolder, imageName);
                using (var memoryStream = new MemoryStream())
                {
                    // Copy the file stream to memory stream
                    await imageFile.CopyToAsync(memoryStream);
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    // Load the image from memory stream
                    using (var image = await Image.LoadAsync(memoryStream))
                    {
                        // Resize the image (e.g., to 2/3 of the original size)
                        int newWidth = (int)(image.Width * 2 / 3);
                        int newHeight = (int)(image.Height * 2 / 3);

                        image.Mutate(x => x.Resize(newWidth, newHeight));

                        // Save the image with compression
                        var encoder = new JpegEncoder
                        {
                            Quality = 75 // Adjust quality here
                        };

                        await image.SaveAsync(imageFilePath, encoder);
                    }
                }
            }
        }

        public static async void UpdloadImageAsyncOld(IWebHostEnvironment hostEnvironment, string yourFolder, string imageName, IFormFile imageFile)
        {
            if (imageFile != null)
            {
                var wwwRootPath = hostEnvironment.WebRootPath;
                var imageUploadFolder = Path.Combine(wwwRootPath, yourFolder);
                if (!Directory.Exists(imageUploadFolder))
                {
                    Directory.CreateDirectory(imageUploadFolder);
                }
                var imageFilePath = Path.Combine(imageUploadFolder, imageName);
                using (var fileStream = new FileStream(imageFilePath, FileMode.Create))
                {
                    await imageFile.CopyToAsync(fileStream);
                    await fileStream.FlushAsync();
                }
            }
        }

        private static void TrimStringProperties<T>(T obj)
        {
            var properties = typeof(T).GetProperties();
            foreach (var property in properties)
            {
                if (property.PropertyType == typeof(string))
                {
                    var value = (string)property.GetValue(obj);
                    if (value != null)
                    {
                        value = value.Trim();
                        property.SetValue(obj, value);
                    }
                }
            }
        }


        // --------- CSV FILES ----------
        public static async Task<bool> UploadCsvFile(IWebHostEnvironment hostEnvironment, string yourFolder, IFormFile file)
        {
            try
            {
                string fileDir = Path.Combine(hostEnvironment.WebRootPath, yourFolder);
                if (!Directory.Exists(fileDir))
                {
                    Directory.CreateDirectory(fileDir);
                }
                string fileName = Path.Combine(fileDir, file.FileName);
                using (var fileStream = new FileStream(fileName, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                    await fileStream.FlushAsync();
                }
            }
            catch (Exception e)
            {
                Console.Error.WriteLine("ERROR UPLOAD: "+e.StackTrace);
                throw e;
            }
            return true;
        }

        public static bool CreateNewCsv<T>(IWebHostEnvironment hostEnvironment, string yourFolder, string fileName, List<T> lines)
        {
            var path = Path.Combine(hostEnvironment.WebRootPath, yourFolder, "New", fileName);
            using (var write = new StreamWriter(path))
            using (var csv = new CsvWriter(write, CultureInfo.InvariantCulture))
            {
                csv.WriteRecords<T>(lines);
            }
            return true;
        }

        public static List<T> ReadCsv<T>(IWebHostEnvironment hostEnvironment, string csvFolder,string fileName)
        {
            List<T> csvLines = new List<T>();

            var path = Path.Combine(hostEnvironment.WebRootPath, csvFolder, fileName);
            var csvConfig = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                Delimiter = ","
            };
            Console.WriteLine($"PATH DU CSV {fileName} => {path}");
            using (var reader = new StreamReader(path))
            using (var csv = new CsvReader(reader, csvConfig))
            {
                csv.Read();
                csv.ReadHeader();
                while (csv.Read())
                {
                    var csvLine = csv.GetRecord<T>();
                    TrimStringProperties(csvLine);
                    Console.WriteLine($"Add CSV LINE: {csvLine}");
                    csvLines.Add(csvLine);
                }
            }
            Console.WriteLine("**** NOMBRE FINAL ==>"+csvLines.Count);

            return csvLines;
        }

        // ------------------------------

        public static object? GetKeyValue(object obj,Type objType)
        {
            PropertyInfo[] properties = objType.GetProperties();
            foreach (PropertyInfo property in properties)
            {
                bool isKey = property.IsDefined(typeof(KeyAttribute), inherit: false);
                if (isKey)
                {
                    return property.GetValue(obj);
                }
            }
            return null;
        }

        public static void AffectUpdatedField<T>(object from, object to)
        {
            Type type = typeof(T);
            PropertyInfo[] properties = type.GetProperties();
            foreach (PropertyInfo property in properties)
            {
                object? propValue = property.GetValue(from);
                if (propValue != null)
                {
                    if(propValue.GetType().IsEquivalentTo(typeof(DateTime)))
                    {
                        if (!propValue.Equals(DateTime.MinValue))
                        {
                            property.SetValue(to, propValue);
                        }
                    }else if (propValue.GetType().IsClass)
                    {
                        Console.WriteLine($"{property.Name} de {nameof(T)} est une class");
                        if(GetKeyValue(propValue,propValue.GetType()) != GetKeyValue(to, to.GetType()))
                        {
                            Console.WriteLine($"Valeur differente du precedent pour le champ {property.Name}");
                            property.SetValue(to, propValue);
                        }
                    }else
                    {
                        if (propValue != property.GetValue(to) && !String.IsNullOrWhiteSpace(propValue.ToString()))
                        {
                            property.SetValue(to, propValue);
                        }
                    }
                }
            }
        }

        public static List<T> Trier<T>(IQueryable<T> query, string triColumn, string orderType)
        {
            if (String.IsNullOrWhiteSpace(orderType))
            {
                return query.OrderBy(triColumn + " asc").ToList();
            }
            else
            {
                if (orderType.Equals("desc"))
                {
                    return query.OrderBy(triColumn + " desc").ToList();
                }
                else
                {
                    return query.OrderBy(triColumn + " asc").ToList();
                }
            }
        }

        public static string HashPassword(string word)
        {
            PasswordHasher<object> hasher = new PasswordHasher<object>();
            return hasher.HashPassword("", word);
        }
        public static bool VerifyPassword(string hashed,string provided)
        {
            PasswordHasher<object> hasher = new PasswordHasher<object>();
            PasswordVerificationResult result = hasher.VerifyHashedPassword("", hashed, provided);

            return result == PasswordVerificationResult.Success;
        }

        public static string GetAuthId(HttpContext httpContext, string role, string key)
        {
            string authId = "";
            
            ClaimsPrincipal claimEquipe = httpContext.User;
            if (claimEquipe.Identity != null)
            {
                if (claimEquipe.Identity.IsAuthenticated)
                {
                    if (claimEquipe.IsInRole(role))
                    {
                        authId = claimEquipe.FindFirstValue(key);
                    }
                }
            }

            return authId;
        }

Evaluation/Controllers/UtilsController.cs
using Evaluation.Models.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PuppeteerSharp.Media;
using System.Text;
using System.Text.RegularExpressions;

namespace Evaluation.Controllers
{
    [AllowAnonymous]
    public class UtilsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginModel()
        {
            return View();
        }

        public IActionResult AllForms()
        {
            return View();
        }

        public IActionResult Tableau()
        {
            return View();
        }

        public IActionResult TableauDeBord()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Histogramme(string anneestring)
        {
            int annee = int.Parse(anneestring);

            try
            {
                /*
                    List<MontantParMois> montantsParMois = new List<MontantParMois>();
                    for(int mois = 1; mois<=12; mois++)
                    {
                        var montant = _psqlContext.Devis
                            .Where(d => d.DateCreation.Year == annee && d.DateCreation.Month == mois)
                            .Sum(d => (double?)d.MontantTotal) ?? 0;

                        montantsParMois.Add(new MontantParMois
                        {
                            Mois = new DateTime(annee, mois, 1).ToString("MMMM"),
                            TotalMontant = montant
                        });
                    }
                    
                    return Json(new {resut = true, data = montantsParMois});
                 */

                return Json("success");
            }
            catch (Exception e)
            {
                Console.Error.WriteLine("ERROR: "+e.Message);
                return Json(new { result = false, error = e.Message });
            }
        }

        [HttpGet]
        public IActionResult ExportExample()
        {
            return View();
        }

        public record RequestData(string htmlContent, string fileName);

        [HttpPost]
        public async Task<FileResult> ExportPdf([FromBody] RequestData requestData)
        {
            Stream pdfStream = await Export.ExportPdfAsync(requestData.htmlContent);

            return File(pdfStream, "application/pdf", requestData.fileName + ".pdf");
        }

        [HttpPost]
        public async Task<FileResult> ExportPdfA3([FromBody] RequestData requestData)
        {
            Stream pdfStream = await Export.ExportPdfAsync(requestData.htmlContent, PaperFormat.A3);

            return File(pdfStream, "application/pdf", requestData.fileName + ".pdf");
        }

        [HttpPost]
        public async Task<FileResult> ExportPdfA4([FromBody] RequestData requestData)
        {
            Stream pdfStream = await Export.ExportPdfAsync(requestData.htmlContent, PaperFormat.A4);

            return File(pdfStream, "application/pdf", requestData.fileName + ".pdf");
        }

        [HttpPost]
        public FileResult ExportExcel([FromBody] RequestData requestData)
        {
            return File(Encoding.UTF8.GetBytes(requestData.htmlContent), "application/vnd.ms-excel", requestData.fileName + ".xls");
        }

        [HttpGet]
        public IActionResult Certificat()
        {
            return View();
        }
    }
}

Evaluation/Views/Utils/AllForms.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="bd-intro mt-2">
    <div class="d-md-flex flex-md-row align-items-center justify-content-between mb-3">
        <h3>All forms</h3>
    </div>
    <!-- <p class="bd-lead"></p> -->
</div>
<div class="bd-content ps-5 pe-5 pt-4 pb-4 bg-white shadow rounded col-8">
    <form asp-area="" asp-controller="Utils" asp-action="AllForms" method="POST" enctype="multipart/form-data">
        <div class="row">
            <input name="id" type="hidden" class="form-control" id="inputText" required>
            <div class="col-6 mb-3">
                <label for="inputText" class="form-label">Nom</label>
                <input name="nom" type="text" class="form-control" id="inputText" required>
            </div>
            <div class="col-6 mb-3">
                <label for="inputNumber" class="form-label">Numero</label>
                <input name="numero" type="number" step="0.1" class="form-control" id="inputNumber" required>
            </div>
            <div class="col-6 mb-3">
                <label for="inputMail" class="form-label">Mail</label>
                <input name="mail" type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" required>
            </div>
            <div class="col-6 mb-3">
                <label for="inputPassword" class="form-label">Password</label>
                <input name="password" type="password" class="form-control" id="inputPassword" required>
            </div>
            <div class="ms-3 mb-3 form-check form-switch">
                <label class="form-check-label" for="inputCheckbox1">Choix 1</label>
                <input name="check" value="choix1" class="form-check-input" type="checkbox" id="inputCheckbox1">
            </div>
            <div class="ms-3 mb-3 form-check form-switch">
                <label class="form-check-label" for="inputCheckbox2">Choix 2</label>
                <input name="check" value="choix2" class="form-check-input" type="checkbox" id="inputCheckbox2">
            </div>
            <div class="col-6 mb-3">
                <label for="inputSelect" class="form-label">Liste</label>
                <select class="form-select" id="inputSelect">
                    <option value="select 1">Select 1</option>
                    <option value="select 2">Select 2</option>
                </select>
            </div>
            <div class="ms-3 mb-3 form-check">
                <label class="form-check-label" for="inputRadio1">Radio 1</label>
                <input name="radioCheck" class="form-check-input" type="radio" id="inputRadio1">
            </div>
            <div class="ms-3 mb-3 form-check">
                <label class="form-check-label" for="inputRadio2">Radio 2</label>
                <input name="radioCheck" class="form-check-input" type="radio" id="inputRadio2">
            </div>
            <div class="col-6 mb-3 ">
                <label for="inputGroupFile" class="form-label">Import fichier</label>
                <div class="input-group">
                  <input type="file" class="form-control" id="inputGroupFile">
                  <label class="input-group-text" for="inputGroupFile">Upload</label>
                </div>
            </div>
            <div class="col-6 mb-3 ">
                <label for="inputGroupFileImage" class="form-label">Import image</label>
                <div class="input-group">
                  <input type="file" class="form-control" id="inputGroupFileImage" accept="image/*">
                </div>
            </div>
            
            <div class="d-grid gap-2 my-3">
                <button class="btn submit-button" type="submit">Se connecter</button>
            </div>
        </div>
    </form>
</div>

Evaluation/Views/Utils/Certificat.cshtml
<div class="row">
    <div class="Bordure1 col-lg-10 mx-auto my-auto">
        <div class="Bordure2 mx-auto my-auto">
            <div class="Bordure3 mx-auto">
                <div class="row">
                    <div class="col-8 mx-auto text-center my-2">
                        <h1 class="certificat-title">CERTIFICATE</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8 mx-auto text-center my-2">
                        <h3 class="simple-text">1st place of <span class="special-text">Ultimate Team Race</span></h3>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-8 mx-auto text-center">
                        <h1 class="certificat-title">-  EQUIPE ${}  -</h1>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-4 text-center">
                        <p>Signature</p>
                        <hr />
                        <p class="signature">Lorem</p>
                    </div>
                    <div class="col-4 text-center">
                        <p>Points: ${0}</p>
                    </div>
                    <div class="col-4 text-center">
                        <p>Date</p>
                        <hr />
                        <p class="dateCertificat">2024-04-06</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Evaluation/Views/Utils/ExportExample.cshtml
<div class="row" lang="fr-fr" id="content-to-export-pdf">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-info">Liste aléatoire</h4>
                <div class="table-responsive" id="table-to-export-excel">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Numero</th>
                                <th scope="col">Id</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for(int i=1;i<=10;i++)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@Random.Shared.Next(1000,9999)</td>
                                    <td>@DateTime.Now.AddDays(i).ToString("dddd dd MMMM yyyy hh heure")</td>
                                </tr>
                            }
                            <tr>
                                <th>Total: </th>
                                <td style="background-color: green;">@(1000 + 500.25)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<button type="button" class="btn btn-inverse-danger btn-fw btn-icon-text" onclick="exportPdf('TestExportPdf','content-to-export-pdf','/Utils/ExportPdf')">
    <i class="ti-download btn-icon-prepend"></i> Export Pdf
</button>
<button type="button" class="btn btn-inverse-success btn-fw btn-icon-text" onclick="exportExcel('TestExportExcel','table-to-export-excel','/Utils/ExportExcel')">
    <i class="ti-download btn-icon-prepend"></i> Export Excel
</button>

<script type="text/javascript" src="~/js/operations/exportOperations.js"></script>

Evaluation/Views/Utils/LoginModel.cshtml
@{
    Layout = "_Auth";
}

<div class="row w-100 mx-0">
    <div class="col-lg-4 mx-auto">
        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
            <div class="brand-logo">
                <img src="../../assets/images/logo.svg" alt="logo">
            </div>
            <h4>Hello! let's get started</h4>
            <h6 class="font-weight-light">Sign in to continue.</h6>
            <form class="pt-3">
                <div class="form-group">
                    <input type="email" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="mt-3 d-grid gap-2">
                    <a class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" href="../../index.html">SIGN IN</a>
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                    <div class="form-check">
                        <label class="form-check-label text-muted">
                        <input type="checkbox" class="form-check-input"> Keep me signed in </label>
                    </div>
                    <a href="#" class="auth-link text-black">Forgot password?</a>
                </div>
                <div class="mb-2 d-grid gap-2">
                    <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                        <i class="ti-facebook me-2"></i>Connect using facebook 
                    </button>
                </div>
                <div class="text-center mt-4 font-weight-light"> 
                    Don't have an account? <a href="register.html" class="text-primary">Create</a>
                </div>
            </form>
        </div>
    </div>
</div>

Evaluation/Views/Utils/Maps.cshtml
<div class="row" id="mapExample" style="height: 600px;">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card position-relative">
            <div class="card-body">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var map = L.map('mapExample').setView([-18.766947, 46.869107], 6);

    var wmsUrl = 'http://127.0.0.1/cgi-bin/mapserv.exe?map=C:/ms4w/apps/madagascar/madagascar.map';

    var buildings = L.tileLayer.wms(wmsUrl, {
        layers: 'buildings',
        format: 'image/png',
        transparent: true
    });

    var landuse = L.tileLayer.wms(wmsUrl, {
        layers: 'landuse',
        format: 'image/png',
        transparent: true
    });

    var natural = L.tileLayer.wms(wmsUrl, {
        layers: 'natural',
        format: 'image/png',
        transparent: true
    });

    var places = L.tileLayer.wms(wmsUrl, {
        layers: 'places',
        format: 'image/png',
        transparent: true
    });

    var pofw = L.tileLayer.wms(wmsUrl, {
        layers: 'pofw',
        format: 'image/png',
        transparent: true
    });

    var pois = L.tileLayer.wms(wmsUrl, {
        layers: 'POIs',
        format: 'image/png',
        transparent: true
    });

    var railways = L.tileLayer.wms(wmsUrl, {
        layers: 'railways',
        format: 'image/png',
        transparent: true
    });

    var roads = L.tileLayer.wms(wmsUrl, {
        layers: 'roads',
        format: 'image/png',
        transparent: true
    });

    var traffic = L.tileLayer.wms(wmsUrl, {
        layers: 'traffic',
        format: 'image/png',
        transparent: true
    });

    var transport = L.tileLayer.wms(wmsUrl, {
        layers: 'transport',
        format: 'image/png',
        transparent: true
    });

    var water = L.tileLayer.wms(wmsUrl, {
        layers: 'water',
        format: 'image/png',
        transparent: true
    });

    var waterways = L.tileLayer.wms(wmsUrl, {
        layers: 'waterways',
        format: 'image/png',
        transparent: true
    });

    var baseLayers = {
        "Buildings": buildings,
        "Roads": roads
    };

    var overlayLayers = {
        "Waterways": waterways,
        "Landuse": landuse,
        "Natural": natural,
        "Places": places,
        "POIs": pois,
        "Railways": railways,
        "Traffic": traffic,
        "Transport": transport,
        "Pofw": pofw,
        "Water": water
    };

    // controles de couches
    L.control.layers(baseLayers, overlayLayers).addTo(map);

    // couches par defaut
    buildings.addTo(map);
    roads.addTo(map);

</script>

Evaluation/Views/Utils/TableauDeBord.cshtml
<div class="row">
    <div class="col-md-6 mb-4 stretch-card transparent">
        <div class="card card-tale">
            <div class="card-body">
                <p class="mb-4">Today’s Receipts</p>
                <p class="fs-30 mb-3">@String.Format("{0:N2}", 4000000) Ar</p>
                <p>10.00% (30 days)</p>
            </div>
        </div>
    </div>
    <div class="col-md-6 mb-4 stretch-card transparent">
        <div class="card card-dark-blue">
            <div class="card-body">
                <p class="mb-4">Total Bookings</p>
                <p class="fs-30 mb-3">@String.Format("{0:N0}", 61344)</p>
                <p>22.00% (30 days)</p>
            </div>
        </div>
    </div>
    <div class="col-lg-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="container-fluid">
                    <div class="d-flex">
                        <input class="form-control me-2" id="annee-devis" value="2024" type="number" placeholder="Annee" aria-label="Annee">
                        <button class="btn btn-outline-secondary" onclick="fetchHistogrammeDevis('/Admin/TableauDeBord','POST')">Voir</button>
                    </div>
                    <div class="d-grid gap-2 my-3">
                        <div class="alert alert-danger alert-dismissible fade show" id="errorDefaultDisplay" role="alert">
                            <strong>Holy macaroni! </strong><span id="errorContent"></span>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Bar chart</h4>
                <canvas id="barChart" width="749" height="374" style="display: block; box-sizing: border-box; height: 187px; width: 374px;"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="~/template/assets/vendors/chart.js/chart.umd.js" defer></script>
<script src="~/template/assets/js/chart.js" defer></script>