Evaluation/Models/ViewModel/Equipe/AddEquipeViewModel.cs
namespace Evaluation.Models.ViewModel
{
    public class AddEquipeViewModel
    {
        public string Nom { get; set; } = "";
        public string Email { get; set; } = "";
        public string MotDePasse { get; set; } = "";
        public string ConfirmMotDePasse { get; set; } = "";
        public string Profil { get; set; } = "Equipe";
        public DateTime DateCreation { get; set; } = DateTime.Now;
    }
}

Evaluation/Models/ViewModel/Equipe/AffectationCoureurViewModel.cs
using Evaluation.Models.Entity;

namespace Evaluation.Models.ViewModel
{
    public class AffectationCoureurViewModel
    {
        public List<Coureur> Coureurs { get; set; } = new List<Coureur>();

        public List<Coureur> CoureurAffectes { get; set; } = new List<Coureur>();
        public Etape Etape { get; set; }
    }
}

Evaluation/Models/ViewModel/Equipe/ClassementGeneraleEquipeViewModel.cs
using Evaluation.Models.Entity;
using Evaluation.Models.MappingView;

namespace Evaluation.Models.ViewModel
{
    public class ClassementGeneraleEquipeViewModel
    {
        public Course Course { get; set; }
        public Categorie Categorie { get; set; }
        public List<ClassementGeneraleEquipe> ClassementGeneraleEquipes { get; set; } = new List<ClassementGeneraleEquipe>();
    }
}

Evaluation/Models/ViewModel/Equipe/EquipeHomeViewModel.cs
using Evaluation.Models.Entity;
using Evaluation.Models.Obj;

namespace Evaluation.Models.ViewModel
{
    public class EquipeHomeViewModel
    {
        public Equipe Equipe { get; set; }
        public List<CoureursEtape> CoureursEtapes { get; set; } = new List<CoureursEtape>();
    }
}

Evaluation/Models/ViewModel/Equipe/EtapeEquipeViewModel.cs
using Evaluation.Models.Entity;

namespace Evaluation.Models.ViewModel
{
    public class EtapeEquipeViewModel
    {
        public Course Course { get; set; }
        public List<Etape> Etapes { get; set; } = new List<Etape>();
    }
}

Evaluation/Models/ViewModel/Equipe/LoginEquipeViewModel.cs
namespace Evaluation.Models.ViewModel
{
    public class LoginEquipeViewModel
    {
        public string Email { get; set; } = "";
        public string MotDePasse { get; set; } = "";
        public bool KeepLoggedIn { get; set; }
    }
}

Evaluation/Controllers/ClassementController.cs
using Evaluation.Models.Cnx;
using Evaluation.Models.Entity;
using Evaluation.Models.MappingView;
using Evaluation.Models.Utils;
using Evaluation.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Evaluation.Controllers
{
    public class ClassementController : Controller
    {
        private readonly PsqlContext _psqlContext;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ClassementController(PsqlContext psqlContext, IWebHostEnvironment hostEnvironment)
        {
            _psqlContext = psqlContext;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Equipe")]
        public async Task<IActionResult> ClassementGeneraleParEtape(string courseId, string triColumn, string order)
        {
            if (String.IsNullOrWhiteSpace(triColumn))
            {
                triColumn = "Rang";
            }

            string nextOrder = "asc";
            if (!String.IsNullOrWhiteSpace(order))
            {
                if (order.Equals("asc")) nextOrder = "desc";
            }

            List<EtapeClassementViewModel> etapeClassements = new List<EtapeClassementViewModel>();

            List<Etape> etapes = await _psqlContext.Etape.Where(e => e.CourseId == Guid.Parse(courseId)).ToListAsync();
            foreach(Etape etape in etapes)
            {
                etapeClassements.Add(new EtapeClassementViewModel
                {
                    Etape = etape,
                    Classements = etape.GetClassement(_psqlContext, nextOrder, triColumn)
                });
            }

            Course course = await _psqlContext.Course.FirstAsync(c => c.Id == Guid.Parse(courseId));
            ViewBag.Course = course;

            ClaimsPrincipal claimsUser = HttpContext.User;
            if(claimsUser.Identity != null)
            {
                if (claimsUser.Identity.IsAuthenticated)
                {
                    if (claimsUser.IsInRole("Admin"))
                    {
                        ViewData["Layout"] = "_Admin";
                    }
                    else if (claimsUser.IsInRole("Equipe"))
                    {
                        ViewData["Layout"] = "_Equipe";
                    }
                }
            }
            return View(etapeClassements);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Equipe")]
        public async Task<IActionResult> ClassementGeneraleParEquipe(string courseId, string triColumn, string order)
        {
            if (String.IsNullOrWhiteSpace(triColumn))
            {
                triColumn = "TotalPoints";
            }

            string nextOrder = "asc";
            if (!String.IsNullOrWhiteSpace(order))
            {
                if (order.Equals("asc")) nextOrder = "desc";
            }

            List<EquipeClassementViewModel> equipeClassements = new List<EquipeClassementViewModel>();

            List<Equipe> equipes = await _psqlContext.Equipe.ToListAsync();
            foreach(Equipe equipe in equipes)
            {
                equipeClassements.Add(new EquipeClassementViewModel
                {
                    Equipe = equipe,
                    Classements = equipe.GetClassement(_psqlContext, nextOrder, triColumn)
                });
            }

            Course course = await _psqlContext.Course.FirstAsync(c => c.Id == Guid.Parse(courseId));
            ViewBag.Course = course;

            ClaimsPrincipal claimsUser = HttpContext.User;
            if (claimsUser.Identity != null)
            {
                if (claimsUser.Identity.IsAuthenticated)
                {
                    if (claimsUser.IsInRole("Admin"))
                    {
                        ViewData["Layout"] = "_Admin";
                    }
                    else if (claimsUser.IsInRole("Equipe"))
                    {
                        ViewData["Layout"] = "_Equipe";
                    }
                }
            }
            return View(equipeClassements);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ClassementHomeAdmin()
        {
            Course? course = await _psqlContext.Course
                .Include(c => c.Etapes)
                    .ThenInclude(e => e.Resultats)
                .Include(c => c.Etapes)
                    .ThenInclude(e => e.Coureurs)
                .FirstOrDefaultAsync();

            if (course == null)
            {
                TempData["ErrorMessage"] = "Aucune course disponible dans la base";
                return RedirectToAction("Profil", "Admin");
            }

            List<Equipe> equipes = await _psqlContext.Equipe.ToListAsync();
            List<Etape> etapes = await _psqlContext.Etape.ToListAsync();

            ClassementHomeAdminViewModel viewModel = new ClassementHomeAdminViewModel
            {
                Course = course,
                Equipes = equipes,
                Etapes = etapes
            };
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Equipe")]
        public async Task<IActionResult> ClassementHomeEquipe()
        {
            Course? course = await _psqlContext.Course
                .Include(c => c.Etapes)
                    .ThenInclude(e => e.Resultats)
                .Include(c => c.Etapes)
                    .ThenInclude(e => e.Coureurs)
                .FirstOrDefaultAsync();

            if (course == null)
            {
                TempData["ErrorMessage"] = "Aucune course disponible dans la base";
                return RedirectToAction("Profil", "Admin");
            }

            List<Etape> etapes = await _psqlContext.Etape.ToListAsync();

            ClassementHomeEquipeViewModel viewModel = new ClassementHomeEquipeViewModel
            {
                Course = course,
                Etapes = etapes
            };
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Equipe")]
        public async Task<IActionResult> ResultatClassementEquipe(string courseId, string equipeId, string triColumn, string order)
        {
            if (String.IsNullOrWhiteSpace(equipeId))
            {
                equipeId = Functions.GetAuthId(HttpContext, "Equipe", "UserId");
            }

            if (String.IsNullOrWhiteSpace(triColumn))
            {
                triColumn = "TotalPoints";
            }

            string nextOrder = "asc";
            if (!String.IsNullOrWhiteSpace(order))
            {
                if (order.Equals("asc")) nextOrder = "desc";
            }
            ViewBag.order = nextOrder;

            Course course = await _psqlContext.Course.FirstAsync(c => c.Id == Guid.Parse(courseId));
            ViewBag.Course = course;

            Equipe equipe = await _psqlContext.Equipe.FirstAsync(e => e.Id == Guid.Parse(equipeId));

            List<ClassementEquipe> classementEquipes = equipe.GetClassement(_psqlContext, order, triColumn);
            ResultatClassementViewModel viewModel = new ResultatClassementViewModel
            {
                Course = course,
                Equipe = equipe,
                ClassementEquipes = classementEquipes
            };

            ClaimsPrincipal claimsUser = HttpContext.User;
            if (claimsUser.Identity != null)
            {
                if (claimsUser.Identity.IsAuthenticated)
                {
                    if (claimsUser.IsInRole("Admin"))
                    {
                        ViewData["Layout"] = "_Admin";
                    }
                    else if (claimsUser.IsInRole("Equipe"))
                    {
                        ViewData["Layout"] = "_Equipe";
                    }
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Equipe")]
        public async Task<IActionResult> ResultatClassementEtape(string courseId, string etapeId, string triColumn, string order)
        {
            if (String.IsNullOrWhiteSpace(triColumn))
            {
                triColumn = "Rang";
            }

            string nextOrder = "asc";
            if (!String.IsNullOrWhiteSpace(order))
            {
                if (order.Equals("asc")) nextOrder = "desc";
            }
            ViewBag.order = nextOrder;

            Course course = await _psqlContext.Course.FirstAsync(c => c.Id == Guid.Parse(courseId));
            ViewBag.Course = course;

            Etape etape = await _psqlContext.Etape.FirstAsync(e => e.Id == Guid.Parse(etapeId));

            List<Classement> classements = etape.GetClassement(_psqlContext, order, triColumn);
            ResultatClassementViewModel viewModel = new ResultatClassementViewModel
            {
                Course = course,
                Etape = etape,
                Classements = classements
            };

            ClaimsPrincipal claimsUser = HttpContext.User;
            if (claimsUser.Identity != null)
            {
                if (claimsUser.Identity.IsAuthenticated)
                {
                    if (claimsUser.IsInRole("Admin"))
                    {
                        ViewData["Layout"] = "_Admin";
                    }
                    else if (claimsUser.IsInRole("Equipe"))
                    {
                        ViewData["Layout"] = "_Equipe";
                    }
                }
            }

            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Equipe")]
        public async Task<IActionResult> ClassementEquipe()
        {
            string role = "";

            ClaimsPrincipal claimsUser = HttpContext.User;

Evaluation/ViewComponents/ListeCourseEquipeViewComponent.cs
using Evaluation.Models.Cnx;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Evaluation.ViewComponents
{
    public class ListeCourseEquipeViewComponent : ViewComponent
    {
        private readonly PsqlContext _psqlContext;

        public ListeCourseEquipeViewComponent(PsqlContext psqlContext)
        {
            _psqlContext = psqlContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var courses = await _psqlContext.Course.ToListAsync();
            return View(courses);
        }
    }
}

Evaluation/Views/Shared/_Auth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Evaluation</title>
    <style class="anchorjs"></style>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

      <!-- plugins:css -->
    <link rel="stylesheet" href="~/template/assets/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/template/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/template/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/template/assets/vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/template/assets/vendors/mdi/css/materialdesignicons.min.css">

    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/template/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.css">
    <link rel="stylesheet" href="~/template/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/template/assets/js/select.dataTables.min.css">

    <link rel="stylesheet" href="~/css/docs.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/template.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dialog.css" asp-append-version="true" />
    <!-- inject:css -->
    <link rel="stylesheet" href="~/template/assets/css/style.css">

    <!-- endinject -->
    <link rel="shortcut icon" href="~/template/assets/images/favicon.png" />
</head>
<body class="bg-light">
    <header></header>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/docs.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*------------ Tsy mandeha ny drop-down raha decommentena ito ambany ----------
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

    <!-- plugins:js -->
    <script src="~/template/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- Plugin js for this page -->
    <script src="~/template/assets/vendors/chart.js/chart.umd.js"></script>
    <script src="~/template/assets/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/template/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.js"></script>
    <script src="~/template/assets/js/dataTables.select.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/template/assets/js/off-canvas.js"></script>
    <script src="~/template/assets/js/template.js"></script>
    <script src="~/template/assets/js/settings.js"></script>
    <script src="~/template/assets/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/template/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="~/template/assets/js/dashboard.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Evaluation/Views/Shared/_Equipe.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Evaluation</title>
    <style class="anchorjs"></style>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

      <!-- plugins:css -->
    <link rel="stylesheet" href="~/template/assets/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/template/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/template/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/template/assets/vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/template/assets/vendors/mdi/css/materialdesignicons.min.css">

    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/template/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.css">
    <link rel="stylesheet" href="~/template/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/template/assets/js/select.dataTables.min.css">

    <link rel="stylesheet" href="~/css/docs.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/template.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dialog.css" asp-append-version="true" />
    <!-- inject:css -->
    <link rel="stylesheet" href="~/template/assets/css/style.css">

    <!-- endinject -->
    <link rel="shortcut icon" href="~/template/assets/images/favicon.png" />

    <!-- Leaflet -->
    <link rel="stylesheet" href="~/js/leaflet/leaflet.css" />
    <script src="~/js/leaflet/leaflet.js"></script>
</head>
<body class="bg-light">
    <header></header>
    <div class="container-scroller">
        @* --------- horizontal navbar ----------*@
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
                <a class="navbar-brand brand-logo me-5" href="index.html"><img src="~/images/TeamRace.png" class="me-2"
                    alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/images/TeamRace.png"
                    alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>
                <ul class="navbar-nav mr-lg-2">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                            <span class="input-group-text" id="search">
                                <i class="icon-search"></i>
                            </span>
                            </div>
                            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now"
                            aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#"
                            data-bs-toggle="dropdown">
                            <i class="icon-bell mx-0"></i>
                            <span class="count"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                            aria-labelledby="notificationDropdown">
                            <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
                            <a class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-success">
                                        <i class="ti-info-alt mx-0"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <h6 class="preview-subject font-weight-normal">Application Error</h6>
                                    <p class="font-weight-light small-text mb-0 text-muted"> Just now </p>
                                </div>
                            </a>
                            <a class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-warning">
                                        <i class="ti-settings mx-0"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <h6 class="preview-subject font-weight-normal">Settings</h6>
                                    <p class="font-weight-light small-text mb-0 text-muted"> Private message </p>
                                </div>
                            </a>
                            <a class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-info">
                                        <i class="ti-user mx-0"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <h6 class="preview-subject font-weight-normal">New user registration</h6>
                                    <p class="font-weight-light small-text mb-0 text-muted"> 2 days ago </p>
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" id="profileDropdown">
                            <img src="~/template/assets/images/faces/face28.jpg" alt="profile" />
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item">
                                <i class="ti-settings text-primary"></i> 
                                Settings 
                            </a>
                            <a class="dropdown-item">
                                <i class="ti-power-off text-primary"></i> 
                                Logout 
                            </a>
                        </div>
                    </li>
                    <li class="nav-item nav-settings d-none d-lg-flex">
                        <a class="nav-link" href="#">
                            <i class="icon-ellipsis"></i>
                        </a>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                    <span class="icon-menu"></span>
                </button>
            </div>
        </nav>
        @* ------------- end navbar -------------*@

        <div class="container-fluid page-body-wrapper">
            @* --------- vertical sidebar ----------*@
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("EquipeHome","Equipe")">
                            <i class="icon-home menu-icon"></i>
                            <span class="menu-title">Accueil</span>
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#utilisateur" aria-expanded="false" aria-controls="utilisateur">
                            <i class="icon-head menu-icon"></i>
                            <span class="menu-title">Utilisateur</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="utilisateur">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" href="@Url.Action("ProfilEquipe", "Equipe")"> Profil </a></li>
                            </ul>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ClassementHomeEquipe","Classement")">
                            <i class="icon-layout menu-icon"></i>
                            <span class="menu-title">Classement coureurs</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("ClassementEquipe","Classement")">
                            <i class="icon-layout menu-icon"></i>
                            <span class="menu-title">Classement equipes</span>
                        </a>
                    </li>

                    @await Component.InvokeAsync("ListeCourseEquipe")
                    
                </ul>
            </nav>
            @* ------------ end sidebar ------------*@

            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <footer class="footer">
                  <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright Evaluation © 2024. All rights reserved.</span>
                    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i
                        class="ti-heart text-danger ms-1"></i></span>
                  </div>
                </footer>
            </div>
        </div>
    </div>

    <script>
        @if (TempData["ErrorMessage"] != null)
        {
            <text>
                alert('@TempData["ErrorMessage"]');
            </text>
        }
    </script>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/docs.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*------------ Tsy mandeha ny drop-down raha decommentena ito ambany ----------
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

    <!-- plugins:js -->
    <script src="~/template/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- Plugin js for this page -->
    <script src="~/template/assets/vendors/chart.js/chart.umd.js"></script>
    <script src="~/template/assets/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/template/assets/vendors/datatables.net-bs5/dataTables.bootstrap5.js"></script>
    <script src="~/template/assets/js/dataTables.select.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/template/assets/js/off-canvas.js"></script>
    <script src="~/template/assets/js/template.js"></script>
    <script src="~/template/assets/js/settings.js"></script>
    <script src="~/template/assets/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/template/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="~/template/assets/js/dashboard.js"></script>

    <script src="~/lib/charts/Chart.bundle.js" asp-append-version="true"></script>
    <script src="~/lib/charts/chartjs.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>