Evaluation/Models/ViewModel/Import/ImportCsvViewModel.cs
namespace Evaluation.Models.ViewModel.Import
{
    public class ImportCsvViewModel
    {
        public IFormFile CsvFile { get; set; }
    }
}

Evaluation/Models/ViewModel/Import/ImportMTDPViewModel.cs
namespace Evaluation.Models.ViewModel
{
    public class ImportMTDPViewModel
    {
        public IFormFile MaisonTravauxCsv { get; set; }
        public IFormFile DevisCsv { get; set; }
        public IFormFile PaimentCsv { get; set; }
    }
}

Evaluation/Models/ViewModel/Import/ImportationViewModel.cs
namespace Evaluation.Models.ViewModel
{
    public class ImportationViewModel
    {
        public IFormFile EtapesFile { get; set; }
        public IFormFile ResultatFile { get; set; }
        public IFormFile PointsFile { get; set; }
    }
}

Evaluation/Models/ViewModel/Import/ValidationImportViewModel.cs
using Evaluation.Models.MappingFile;

namespace Evaluation.Models.ViewModel.Import
{
    [Serializable]
    public class ValidationImportViewModel
    {
        //public ImportCsvResult<CsvMaisonTravaux> MaisonTravauxResults { get; set; }
        //public ImportCsvResult<CsvDevis> DevisResults { get; set; }
        //public ImportCsvResult<CsvPaiement> PaiementResults { get; set; }
    }
}

Evaluation/Controllers/ImportController.cs
using Evaluation.Models.Cnx;
using Evaluation.Models.MappingFile;
using Evaluation.Models.ViewModel;
using Evaluation.Models.ViewModel.Import;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Evaluation.Controllers
{
    public class ImportController : Controller
    {
        private readonly PsqlContext _psqlContext;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly string _csvFolder = "upload/csv";

        public ImportController(PsqlContext psqlContext,IWebHostEnvironment hostEnvironment)
        {
            _psqlContext = psqlContext;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ImportCsv()
        {
            return View();
        }

        /*
        [HttpPost]
        public async Task<JsonResult> ImportCsvJson(IFormFile file)
        {
            ImportCsvResult? result = null;
            try
            {
                bool uploaded = await Functions.UploadCsvFile(_hostEnvironment, _csvFolder, file);
                if (uploaded)
                {
                    List<PersonAccountLine> personAccountLines = Functions.ReadCsv<PersonAccountLine>(_hostEnvironment, _csvFolder, file.FileName);
                    result = new PersonAccountCsv().ImportCsvToDatabase(personAccountLines);
                }
            }
            catch (Exception e)
            {
                Console.Error.WriteLine("ERROR: \n", e);
                ViewBag.ErrorMessage = e.Message;
            }
            Console.WriteLine("Resultat retournés");
            return Json(result);
        }
        */
        // --------------------------------------------------------------
        

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult ValidationImport()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult ImportationEtapeResultat()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ImportationEtapeResultat(ImportationViewModel viewModel)
        {

            using (var transaction = _psqlContext.Database.BeginTransaction())
            {
                try
                {
                    if(viewModel.EtapesFile == null || viewModel.ResultatFile == null)
                    {
                        throw new Exception("Veuillez remplir les cases vides");
                    }

                    ImportCsvResult<CsvEtape> importEtapeCsvResult = await new CsvEtape().DispatchToTableAsync(_psqlContext, _hostEnvironment, _csvFolder, viewModel.EtapesFile);
                    ImportCsvResult<CsvResultat> importResultatResult = await new CsvResultat().DispatchToTableAsync(_psqlContext, _hostEnvironment, _csvFolder, viewModel.ResultatFile);

                    transaction.Commit();
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine(e.StackTrace);
                    transaction.Rollback();
                    ViewBag.ErrorMessage = e.Message;
                }
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult ImportationPoints()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ImportationPoints(ImportationViewModel viewModel)
        {
            using (var transaction = _psqlContext.Database.BeginTransaction())
            {
                try
                {
                    if (viewModel.PointsFile == null)
                    {
                        throw new Exception("Veuillez remplir les cases vides");
                    }

                    ImportCsvResult<CsvPoints> importPointsResult = await new CsvPoints().DispatchToTableAsync(_psqlContext, _hostEnvironment, _csvFolder, viewModel.PointsFile);
                    
                    transaction.Commit();
                }
                catch (Exception e)
                {
                    Console.Error.WriteLine(e.StackTrace);
                    transaction.Rollback();
                    ViewBag.ErrorMessage = e.Message;
                }
            }
            return View();
        }
    }
}

Evaluation/Views/Import/ImportMaisonTravauxDevis.cshtml
@model Evaluation.Models.ViewModel.ImportMTDPViewModel;

<div class="container-xxl popup-dialog-container" id="dialog-container">
    <div class="boolean-dialog col-4" id="current-dialog">
        <div class="toast-body">
            <div class="mt-2 pt-2 border-top" id="ligne-valid">
            </div>
            <div class="mt-2 pt-2 border-top" id="ligne-invalid">
            </div>
            <div class="mt-2 pt-2 border-top">
                <button type="button" class="btn btn-danger btn-sm" onclick="importLinesToTable()">Importer</button>
                <button type="button" class="btn btn-secondary btn-sm" onclick="dismissDialog()">Annuler</button>
            </div>
        </div>
    </div>
</div>


<div class="bd-intro mt-2">
    <div class="d-md-flex flex-md-row align-items-center justify-content-between mb-3">
        <h3>Import csv Maison et devis</h3>
    </div>
    <!-- <p class="bd-lead"></p> -->
</div>
<div class="bd-content ps-5 pe-5 pt-4 pb-4 bg-white shadow rounded col-8">
    <form asp-area="" asp-controller="Import" asp-action="ImportMaisonTravauxDevis" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6 mb-3 ">
                <label for="inputCsvMaisonTravaux" class="form-label">Maison et travaux</label>
                <div class="input-group">
                  <input type="file" class="form-control" id="inputCsvMaisonTravaux" accept="/*" asp-for="MaisonTravauxCsv">
                </div>
            </div>
            <div class="col-6 mb-3 ">
                <label for="inputCsvDevis" class="form-label">Devis</label>
                <div class="input-group">
                  <input type="file" class="form-control" id="inputCsvDevis" accept="/*" asp-for="DevisCsv">
                </div>
            </div>
            <div class="d-grid gap-2 my-3">
                <button class="btn submit-button" type="submit">Importer</button>
            </div>
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="d-grid gap-2 my-3">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      <strong>Error: </strong>@ViewBag.ErrorMessage
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            }
            
        </div>
    </form>
</div>

<script type="text/javascript" defer src="~/js/operations/importCsvMaisonTravauxDevis.js"></script>

Evaluation/Views/Import/ImportPaiement.cshtml
@model Evaluation.Models.ViewModel.ImportMTDPViewModel;

<div class="container-xxl popup-dialog-container" id="dialog-container">
    <div class="boolean-dialog col-4" id="current-dialog">
        <div class="toast-body">
            <div class="mt-2 pt-2 border-top" id="ligne-valid">
            </div>
            <div class="mt-2 pt-2 border-top" id="ligne-invalid">
            </div>
            <div class="mt-2 pt-2 border-top">
                <button type="button" class="btn btn-danger btn-sm" onclick="importLinesToTable()">Importer</button>
                <button type="button" class="btn btn-secondary btn-sm" onclick="dismissDialog()">Annuler</button>
            </div>
        </div>
    </div>
</div>


<div class="bd-intro mt-2">
    <div class="d-md-flex flex-md-row align-items-center justify-content-between mb-3">
        <h3>Import csv de paiement</h3>
    </div>
    <!-- <p class="bd-lead"></p> -->
</div>
<div class="bd-content ps-5 pe-5 pt-4 pb-4 bg-white shadow rounded col-8">
    <form asp-area="" asp-controller="Import" asp-action="ImportPaiement" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6 mb-3 ">
                <label for="inputCsvMaisonTravaux" class="form-label">Paiement</label>
                <div class="input-group">
                  <input type="file" class="form-control" id="inputCsvMaisonTravaux" accept="/*" asp-for="PaimentCsv">
                </div>
            </div>
            <div class="d-grid gap-2 my-3">
                <button class="btn submit-button" type="submit">Importer</button>
            </div>
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="d-grid gap-2 my-3">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      <strong>Error: </strong>@ViewBag.ErrorMessage
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            }
            
        </div>
    </form>
</div>

<script type="text/javascript" defer src="~/js/operations/importCsvMaisonTravauxDevis.js"></script>

Evaluation/Views/Import/ImportationEtapeResultat.cshtml
@using Evaluation.Models.ViewModel
@model ImportationViewModel

<div class="row">
    <div class="col-12 grid-margin mt-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Import Etape et Resultat</h4>
                <form class="form-sample" asp-area="" asp-action="ImportationEtapeResultat" asp-controller="Import" method="POST" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 mx-auto">
                            <div class="col-12 mb-3 ">
                                <label for="inputCsvEtapes" class="form-label">Csv Etapes</label>
                                <div class="input-group">
                                  <input type="file" accept="/*" class="form-control" id="inputCsvEtapes" asp-for="EtapesFile">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 mx-auto">
                            <div class="col-12 mb-3 ">
                                <label for="inputCsvResultats" class="form-label">Csv Résultat</label>
                                <div class="input-group">
                                  <input type="file" accept="/*" class="form-control" id="inputCsvResultats" asp-for="ResultatFile">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mt-2">
                            <div class="form-group row">
                                <div class="col-sm-9">
                                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">IMPORTER</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    @if(ViewBag.ErrorMessage != null){
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>Holy macaroni!</strong> @ViewBag.ErrorMessage
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

Evaluation/Views/Import/ImportationPoints.cshtml
@using Evaluation.Models.ViewModel
@model ImportationViewModel

<div class="row">
    <div class="col-12 grid-margin mt-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Import Points</h4>
                <form class="form-sample" asp-area="" asp-action="ImportationPoints" asp-controller="Import" method="POST" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 mx-auto">
                            <div class="col-12 mb-3 ">
                                <label for="inputCsvEtapes" class="form-label">Csv Points</label>
                                <div class="input-group">
                                  <input type="file" accept="/*" class="form-control" id="inputCsvEtapes" asp-for="PointsFile">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 mt-2">
                            <div class="form-group row">
                                <div class="col-sm-9">
                                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">IMPORTER</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    @if(ViewBag.ErrorMessage != null){
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>Holy macaroni!</strong> @ViewBag.ErrorMessage
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

Evaluation/Views/Import/ValidationImport.cshtml
@model Evaluation.Models.ViewModel.ImportMTDPViewModel;


<div class="bd-intro mt-2">
    <div class="d-md-flex flex-md-row align-items-center justify-content-between mb-3">
        <h3>Veuillez confirmer l'importation </h3>
    </div>
    <!-- <p class="bd-lead"></p> -->
</div>
<div class="bd-content ps-5 pe-5 pt-4 pb-4 bg-white shadow rounded col-8">
    <div class="row">
        <div class="col-6 mb-3 ">
            <label for="inputCsvMaisonTravaux" class="form-label">Maison et travaux</label>
            <div class="input-group">
                <input type="file" class="form-control" id="inputCsvMaisonTravaux" accept="/*" asp-for="MaisonTravauxCsv">
            </div>
        </div>
        <div class="col-6 mb-3 ">
            <label for="inputCsvDevis" class="form-label">Devis</label>
            <div class="input-group">
                <input type="file" class="form-control" id="inputCsvDevis" accept="/*" asp-for="DevisCsv">
            </div>
        </div>
        <div class="mt-2 pt-2 border-top">
            <button type="button" class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("","")'">Importer</button>
            <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("","")'">Annuler</button>
        </div>
            
    </div>
</div>

<script type="text/javascript" defer src="~/js/operations/importCsvMaisonTravauxDevis.js"></script>

Evaluation/Views/Import/importCsv.cshtml
<div class="container-xxl popup-dialog-container" id="dialog-container">
    <div class="boolean-dialog col-4" id="current-dialog">
        <div class="toast-body">
            <div class="mt-2 pt-2 border-top" id="ligne-valid">
            </div>
            <div class="mt-2 pt-2 border-top" id="ligne-invalid">
            </div>
            <div class="mt-2 pt-2 border-top">
                <button type="button" class="btn btn-danger btn-sm" onclick="importLinesToTable()">Importer</button>
                <button type="button" class="btn btn-secondary btn-sm" onclick="dismissDialog()">Annuler</button>
            </div>
        </div>
    </div>
</div>


<div class="bd-intro mt-2">
    <div class="d-md-flex flex-md-row align-items-center justify-content-between mb-3">
        <h3>Import csv</h3>
    </div>
    <!-- <p class="bd-lead"></p> -->
</div>
<div class="bd-content ps-5 pe-5 pt-4 pb-4 bg-white shadow rounded col-8">
    <form id="importCsvForm" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6 mb-3 ">
                <label for="inputCsvFile" class="form-label">Fichier</label>
                <div class="input-group">
                  <input type="file" name="file" class="form-control" id="inputCsvFile" accept="/*">
                </div>
            </div>
            <div class="d-grid gap-2 my-3">
                <button id="importButton" class="btn submit-button" type="button">Importer</button>
            </div>
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="d-grid gap-2 my-3">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      <strong>Error: </strong>@ViewBag.ErrorMessage
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            }
            
        </div>
    </form>
</div>

<script type="text/javascript" defer src="~/js/operations/importCsvPersonAccount.js"></script>