Evaluation/Models/Entity/Penalite.cs
using Evaluation.Models.Cnx;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;

namespace Evaluation.Models.Entity
{
    public class Penalite
    {
        private Guid _id;
        private Guid _etapeId;
        private Etape _etape;
        private Guid _equipeId;
        private Equipe _equipe;
        private TimeSpan _tempsPenalite;
        private int _etat;

        [Key]
        public Guid Id
        {
            get { return _id; }
            set { _id = value; }
        }
        [ForeignKey("Etape")]
        public Guid EtapeId
        {
            get { return _etapeId; }
            set { _etapeId = value; }
        }
        public Etape Etape
        {
            get { return _etape; }
            set { _etape = value; }
        }
        [ForeignKey("Equipe")]
        public Guid EquipeId
        {
            get { return _equipeId; }
            set { _equipeId = value; }
        }
        public Equipe Equipe
        {
            get { return _equipe; }
            set { _equipe = value; }
        }

        public TimeSpan TempsPenalite
        {
            get { return _tempsPenalite; }
            set { _tempsPenalite = value; }
        }

        public int Etat
        {
            get { return _etat; }
            set { _etat = value; }
        }

        public override string? ToString()
        {
            string stringValue = "{";
            Type type = this.GetType();
            PropertyInfo[] properties = type.GetProperties();
            foreach (PropertyInfo property in properties)
            {
                stringValue += property.Name + "=" + property.GetValue(this) + ";";
            }
            stringValue += "}";

            return stringValue;
        }

        // ------------------- FUNCTIONS -------------------

        public async Task<int> AddNewPenalite(PsqlContext context, string etapeId, string equipeId, TimeSpan tempsPenalite)
        {
            int writen = 0;
            using (var transaction = context.Database.BeginTransaction())
            {
                try
                {
                    Etape etape = context.Etape
                        .Include(e => e.Coureurs)
                        .First(e => e.Id == Guid.Parse(etapeId));

                    List<Coureur> coureursEquipeAffectees = etape.Coureurs
                        .Where(c => c.EquipeId == Guid.Parse(equipeId)).ToList();
                    foreach (Coureur coureurAffectee in coureursEquipeAffectees)
                    {
                        Resultat? resultatCoureurThisEtape = await context.Resultat
                            .FirstOrDefaultAsync(r => r.EtapeId == etape.Id && r.CoureurId == coureurAffectee.Id);
                        if(resultatCoureurThisEtape != null)
                        {
                            resultatCoureurThisEtape.DateArrivee = resultatCoureurThisEtape.DateArrivee.Add(tempsPenalite);
                            context.Resultat.Update(resultatCoureurThisEtape);
                        }
                    }

                    Penalite newPenalite = new Penalite
                    {
                        EtapeId = etape.Id,
                        EquipeId = Guid.Parse(equipeId),
                        TempsPenalite = tempsPenalite
                    };

                    await context.Penalite.AddAsync(newPenalite);
                    writen = await context.SaveChangesAsync();

                    await transaction.CommitAsync();
                }
                catch (Exception e)
                {
                    await transaction.RollbackAsync();
                    Console.Error.WriteLine(e.StackTrace);
                    throw e;
                }

                return writen;
            }
        }

        public async Task<int> DeletePenalite(PsqlContext context, string idPenalite)
        {
            int writen = 0;
            using(var transaction = context.Database.BeginTransaction())
            {
                try
                {
                    Penalite? penaliteToDelete = await context.Penalite
                        .Include(p => p.Etape)
                            .ThenInclude(e => e.Coureurs)
                        .FirstOrDefaultAsync(p => p.Id == Guid.Parse(idPenalite));

                    if(penaliteToDelete != null)
                    {
                        List<Coureur> coureursEquipeAffectees = penaliteToDelete.Etape.Coureurs
                        .Where(c => c.EquipeId == penaliteToDelete.EquipeId).ToList();

                        foreach (Coureur coureurAffectee in coureursEquipeAffectees)
                        {
                            Resultat? resultatCoureurThisEtape = await context.Resultat
                            .FirstOrDefaultAsync(r => r.EtapeId == penaliteToDelete.EtapeId && r.CoureurId == coureurAffectee.Id);
                            
                            if (resultatCoureurThisEtape != null)
                            {
                                resultatCoureurThisEtape.DateArrivee = resultatCoureurThisEtape.DateArrivee.Subtract(penaliteToDelete.TempsPenalite);
                                context.Resultat.Update(resultatCoureurThisEtape);
                            }

                            
                        }

                        penaliteToDelete.Etat = -1;
                        context.Penalite.Update(penaliteToDelete);
                        writen = await context.SaveChangesAsync();

                        await transaction.CommitAsync();
                    }
                }
                catch(Exception e)
                {
                    await transaction.RollbackAsync();
                    Console.Error.WriteLine(e.StackTrace);
                    throw e;
                }
            }
            return writen;
        }
    }
}

Evaluation/Models/ViewModel/Penalite/AjoutPenaliteViewModel.cs
using Evaluation.Models.Entity;

namespace Evaluation.Models.ViewModel
{
    public class AjoutPenaliteViewModel
    {
        public string EtapeId { get; set; } = "";
        public string EquipeId { get; set; } = "";
        public TimeOnly TempsPenalite { get; set; }
        public string TempsPenaliteString { get; set; } = "";

        public List<Etape> Etapes { get; set; } = new List<Etape>();       
        public List<Equipe> Equipes { get; set; } = new List<Equipe>();

    }
}

Evaluation/Controllers/PenaliteController.cs
using Evaluation.Models.Cnx;
using Evaluation.Models.Entity;
using Evaluation.Models.Utils;
using Evaluation.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Evaluation.Controllers
{
    public class PenaliteController : Controller
    {
        private readonly PsqlContext _psqlContext;
        private readonly IWebHostEnvironment _hostEnvironment;

        public PenaliteController(PsqlContext psqlContext, IWebHostEnvironment hostEnvironment)
        {
            _psqlContext = psqlContext;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult PenaliteHome(int currentPage, int offset, int signe, string order, string triColumn)
        {
            // ------------- tri et pagination --------------
            if (String.IsNullOrWhiteSpace(triColumn))
            {
                triColumn = "Id";
            }

            string nextOrder = "asc";
            if (!String.IsNullOrWhiteSpace(order))
            {
                if (order.Equals("asc")) nextOrder = "desc";
            }

            int limit = 7;
            int total = _psqlContext.Penalite.Count();

            int nextOffset = offset + (limit * signe);
            if (nextOffset < 0 || nextOffset >= total)
            {
                nextOffset = offset;
            }
            // ----------------------------------------------
            IQueryable<Penalite> penalitesQuery = _psqlContext.Penalite
                .Where(p => p.Etat != -1)
                .Include(p => p.Etape)
                .Include(p => p.Equipe)
                .Skip(nextOffset)
                .Take(limit);
            List<Penalite> penalites = Functions.Trier<Penalite>(penalitesQuery, triColumn, order);

            if (offset != nextOffset)
            {
                currentPage += signe;
            }

            ViewBag.offset = nextOffset;
            ViewBag.currentPage = currentPage;
            ViewBag.order = nextOrder;
            return View(penalites);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AjoutPenalite()
        {
            AjoutPenaliteViewModel viewModel = new AjoutPenaliteViewModel
            {
                Etapes = await _psqlContext.Etape.ToListAsync(),
                Equipes = await _psqlContext.Equipe.ToListAsync()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AjoutPenalite(AjoutPenaliteViewModel viewModel)
        {
            // ModelState.AddModelError("TempsArriveeString", "Le format de l'heure est invalide.");
            try
            {
                TimeSpan tempsPenalite = Functions.ParseStringToTimeSpan(viewModel.TempsPenaliteString);
                Console.WriteLine($"=====> TEMP PENALITE: {tempsPenalite}");

                Penalite newPenalite = new Penalite
                {
                    EtapeId = Guid.Parse(viewModel.EtapeId),
                    EquipeId = Guid.Parse(viewModel.EquipeId),
                    TempsPenalite = tempsPenalite
                };

                await _psqlContext.Penalite.AddAsync(newPenalite);
                int writen = await _psqlContext.SaveChangesAsync();


                Console.WriteLine($"    NOMBRE DE LIGNE AFFECTEE  => {writen}");

            }
            catch(Exception e)
            {
                Console.Error.WriteLine(e.StackTrace);
                ViewBag.ErrorMessage = e.Message;
            }

            viewModel.Etapes = await _psqlContext.Etape.ToListAsync();
            viewModel.Equipes = await _psqlContext.Equipe.ToListAsync();

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<JsonResult> Delete(string id)
        {
            Console.WriteLine($"******* Try to Delete {id}");

            Guid guidId = Guid.Parse(id);
            int deleted = 0;

            try
            {
                Penalite? penaliteToDelete = await _psqlContext.Penalite
                        .Include(p => p.Etape)
                            .ThenInclude(e => e.Coureurs)
                        .FirstOrDefaultAsync(p => p.Id == Guid.Parse(id));

                if (penaliteToDelete != null)
                {
                    penaliteToDelete.Etat = -1;
                    _psqlContext.Penalite.Update(penaliteToDelete);
                    deleted = await _psqlContext.SaveChangesAsync();

                    Console.WriteLine("Deleted =====> " + deleted);
                }
            }
            catch (Exception e)
            {
                Console.Error.WriteLine("ERROR: \n" + e.Message);
                return Json(new { result = false, error = e.Message });
            }

            return Json(new { result = true, affected = deleted });
        }
    }
}

Evaluation/Views/Penalite/AjoutPenalite.cshtml
@using Evaluation.Models.Entity
@using Evaluation.Models.ViewModel

@model AjoutPenaliteViewModel

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <a href="@Url.Action("PenaliteHome", "Penalite", new { currentPage = 1, offset = 0, signe = 0 })">
                    <i class="mdi mdi-arrow-left"></i> Retour
                </a>
            </div>
        </div>
    </div>

    <div class="col-12 grid-margin mt-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Ajout de pénalité</h4>
                <form class="form-sample" asp-area="" asp-action="AjoutPenalite" asp-controller="Penalite" method="POST" enctype="multipart/form-data">
                    <div class="row">

                        <div class="col-6 mx-auto my-2">
                            <div class="form-floating">
                                <select asp-for="EtapeId" class="form-select" id="floatingSelectGrid" aria-label="Floating label select example">
                                    @foreach (Etape etape in Model.Etapes)
                                    {
                                        <option value="@etape.Id"> @etape.Nom </option>
                                    }
                                </select>
                                <label for="floatingSelectGrid">Choix étape</label>
                            </div>
                        </div>

                        <div class="col-6 mx-auto my-2">
                            <div class="form-floating">
                                <select asp-for="EquipeId" class="form-select" id="floatingSelectGrid" aria-label="Floating label select example">
                                    @foreach (Equipe equipe in Model.Equipes)
                                    {
                                        <option value="@equipe.Id"> @equipe.Nom </option>
                                    }
                                </select>
                                <label for="floatingSelectGrid">Choix équipe</label>
                            </div>
                        </div>

                        <div class="col-6 mx-auto my-2">
                            <div class="form-floating form-group">
                                <input asp-for="TempsPenaliteString" type="text" value="00:00:00" placeholder="Temps penalite"  step="1" class="form-control form-control-lg" id="inputTempsPenalite">
                                <label for="inputTempsPenalite">Temps de penalité: 00:00:00</label>
                                <span asp-validation-for="TempsPenaliteString" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-6 my-2">
                            <div class="form-group row">
                                <div class="col-sm-9">
                                    <button type="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">Valider</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                
                @if(ViewBag.ErrorMessage != null){
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>Holy macaroni!</strong> @ViewBag.ErrorMessage
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Evaluation/Views/Penalite/PenaliteHome.cshtml
@using Evaluation.Models.Entity
@using Evaluation.Models.Obj
@using Evaluation.Models.Utils
@using Evaluation.Models.ViewModel
@model List<Penalite>

@{
    int currentPage = 1;
    if(ViewBag.currentPage != null)
    {
        currentPage = ViewBag.currentPage;
    }
    int offset = 0;
    if(ViewBag.offset != null)
    {
        offset = ViewBag.offset;
    }
    string order = "asc";
    if(ViewBag.order != null)
    {
        order = ViewBag.order;
    }
}

<div class="container-xxl popup-dialog-container" id="dialog-container">
    <div class="col-lg-4 col-md-6 col-sm-10 col-10 boolean-dialog">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Confirm delete</h5>
                <div class="alert alert-danger alert-dismissible fade show mt-3" id="errorDefaultDisplay" role="alert">
                    <strong>Holy macaroni!</strong> <span id="errorContent"></span>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <div class="pt-3 border-top">
                    <button type="button" class="btn btn-danger btn-md" onclick="deleteEntity()">Delete</button>
                    <button type="button" class="btn btn-secondary btn-md" onclick="dismissDialog()">Discard</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 stretch-card grid-margin grid-margin-md-0 my-3">
        <div class="card data-icon-card-primary">
            <div class="card-body">
                <h3 class="text-white">Gestion de pénalité</h3>
            </div>
        </div>
    </div>

    <div class="col-lg-12 col-md-12">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 my-2">
                <button class="btn btn-outline-primary btn-icon-text" onclick="location.href='@Url.Action("AjoutPenalite", "Penalite")'">
                    <i class="mdi mdi-plus"></i>
                    <span class="d-inline-block text-left">Ajouter Pénalité</span>
                </button>
            </div>
        </div>
    </div>

    <div class="col-lg-12 grid-margin stretch-card my-3">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-info">Liste des pénalités</h4>
                <div class="table-responsive">
                    <table class="table table-striped" id="list-table">
                        <thead>
                            <tr>
                                <th scope="col" onclick="location.href='@Url.Action("PenaliteHome", "Penalite", new { currentPage = currentPage, offset = offset, signe = 0, order = order, triColumn = "Etape" })'"> Etape <i class="mdi mdi-sort"></i></th>
                                <th scope="col" onclick="location.href='@Url.Action("PenaliteHome", "Penalite", new { currentPage = currentPage, offset = offset, signe = 0, order = order, triColumn = "Equipe" })'"> Equipe <i class="mdi mdi-sort"></i></th>
                                <th scope="col" onclick="location.href='@Url.Action("PenaliteHome", "Penalite", new { currentPage = currentPage, offset = offset, signe = 0, order = order, triColumn = "TempsPenalite" })'"> Temps de pénalité <i class="mdi mdi-sort"></i></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(Penalite penalite in @Model)
                            {
                                <tr id="ligne_@penalite.Id">
                                    <td>@penalite.Etape.Nom</td>
                                    <td>@penalite.Equipe.Nom</td>
                                    <td>@Functions.TimeSpanToString(penalite.TempsPenalite)</td>
                                    <td>
                                        <button type="button" class="btn btn-danger btn-icone-text" onclick="toogleDialog('@penalite.Id', 'ligne_@penalite.Id', '/Penalite/Delete', 'POST')"> Delete <i class="ti-trash btn-icon-append"></i></button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="@Url.Action("PenaliteHome", "Penalite", new { currentPage = currentPage, offset = offset, signe = -1, order = order })">Previous</a></li>
        <li class="page-item"><a class="page-link" href="#">@currentPage</a></li>
        <li class="page-item"><a class="page-link" href="@Url.Action("PenaliteHome", "Penalite", new { currentPage = currentPage, offset = offset, signe = 1, order = order })">Next</a></li>
      </ul>
    </nav>
</div>

<script type="text/javascript" src="~/js/operations/delete.js"></script>